### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by kingname** [CUCyber/ja3transport#7]
When I use goroutine, this line panic:

```go
tr, _ := ja3transport.NewTransportWithConfig(browser.Ja3, &config)
``` 

the error msg is:

```
fatal error: concurrent map read and map write

goroutine 21 [running]:
runtime.throw(0x1358b57, 0x21)
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc00004ec20 sp=0xc00004ebf0 pc=0x1036c92
runtime.mapaccess2_faststr(0x12fd980, 0xc00009ac90, 0xc0000ac979, 0x2, 0xc000080e18, 0xc000060101)
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc00004ec90 sp=0xc00004ec20 pc=0x1015465
github.com/CUCyber/ja3transport.stringToSpec(0xc0000ac840, 0x153, 0x100f4b8, 0x170, 0x13497c0)
        /Users/kingname/go/pkg/mod/github.com/!c!u!cyber/ja3transport@v0.0.0-20201031204932-8a22ac8ab5d7/transport.go:152 +0x4db fp=0xc00004ee08 sp=0xc00004ec90 pc=0x12c897b
github.com/CUCyber/ja3transport.NewTransportWithConfig(0xc0000ac840, 0x153, 0xc000001680, 0x0, 0x0, 0x0)
        /Users/kingname/go/pkg/mod/github.com/!c!u!cyber/ja3transport@v0.0.0-20201031204932-8a22ac8ab5d7/transport.go:85 +0x39 fp=0xc00004ee50 sp=0xc00004ee08 pc=0x12c8399
```

it seems that there is a concurrent write on map at line 152 at `transport.go`:

![image](https://user-images.githubusercontent.com/5440523/132216256-9d9c3bbe-a8ec-41b4-8361-b46887f04368.png)

The key reason is the global variable `extMap`:

![image](https://user-images.githubusercontent.com/5440523/132216621-5599abcc-d99a-4eae-9d0a-94fd1899a8bf.png)

**Comment by t94j0** [comment]
Good find. Moving `extMap` into the specToString function will be the quickest way to fix this issue.

**Comment by reneManqueros** [comment]
Sent a PR for this: https://github.com/CUCyber/ja3transport/pull/16
